SELECT I.DESCTRIPTION, IL.NAME 
FROM ISSUES I
JOIN ISSUELISTS IL ON I.ISSUELIST_ID = IL.ID;

SELECT I.DESCTRIPTION, U.FIRSTNAME, U.LASTNAME
FROM ISSUES I
JOIN USERS U ON I.USER_ID_ASSIGNEDTO = U.ID;

SELECT U.FIRSTNAME, U.LASTNAME, COUNT(*) AS NUMBER_OF_TASKS
FROM USERS U JOIN ISSUES I ON U.ID = I.USER_ID_ASSIGNEDTO
GROUP BY I.USER_ID_ASSIGNEDTO
HAVING COUNT(*) > 0
ORDER BY U.LASTNAME, U.FIRSTNAME;